mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^image/', include('upload_form.urls', namespace = 'upload_form')),
]

upload_form/urls.py
from django.conf.urls import url
from upload_form import views

urlpatterns = [
    url(r'(?P<id>\d+)/$', views.lookBy, name = 'form'),
    url(r'^upload_page/', views.form, name = 'form'),
    url(r'^complete/', views.complete, name = 'complete'),
]

upload_form/models.py
from django.db import models
from datetime import datetime

class FileNameModel(models.Model):
    file_name = models.CharField(max_length = 50)
    upload_time = models.DateTimeField(default = datetime.now)

class imageFileModel(models.Model):
    file_data = models.BinaryField()

upload_form/views.py
from django.shortcuts import render_to_response, redirect
from django.template.context_processors import csrf
from django.conf import settings
from django.http.response import HttpResponse
from upload_form.models import FileNameModel
from upload_form.models import imageFileModel
import sys, os
UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'

def form(request):
    if request.method != 'POST':
        c = {}
        c.update(csrf(request))
        return render_to_response('upload_form/form.html', c)

    file = request.FILES['file']
    path = os.path.join(UPLOADE_DIR, file.name)
    destination = open(path, 'wb')

    for chunk in file.chunks():
        destination.write(chunk)

    insert_data = FileNameModel(file_name = file.name)
    insert_data.save()

    return redirect('upload_form:complete')

def complete(request):
    return render_to_response('upload_form/complete.html')

def lookBy(request, id = None):
    fn = FileNameModel.objects.get(pk=id)
    return HttpResponse("<img src='/static/files/" + str(fn.file_name) + "'/>")

upload_form/templates/upload_form/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <title>ファイルアップローダ</title>
    </head>
    <body>
        {% block content %}
            {{ content }}
        {% endblock %}
    </body>
</html>

upload_form/templates/upload_form/complete.html
{% extends "upload_form/base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}
    <div align="center">
        <h1 align="center">アップロード完了</h1>
        <a href="{% url 'upload_form:form' %}"><button>戻る</button></a>
    </div>
{% endblock content %}

upload_form/templates/upload_form/form.html
{% extends "upload_form/base.html" %}

{% block title %}アップローダサンプル{% endblock title %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="submit" value="アップロード">
    </form>
{% endblock content %}